// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 7: el seed se declara acá; `npx prisma db seed` lo ejecuta.
    seed: "npx ts-node --project prisma/tsconfig.json prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
